import { colors, font, radius } from "./tokens";

export const canvasStyles = {
  shell: {
    width: "100%",
    height: "100vh",
    background: colors.background,
    display: "flex",
    flexDirection: "column",
    fontFamily: font.mono,
    color: colors.textSecondary,
    overflow: "hidden",
    userSelect: "none",
  },
  canvas: {
    flex: 1,
    overflow: "hidden",
    cursor: "grab",
    position: "relative",
    background: colors.background,
  },
  grid: {
    position: "absolute",
    inset: 0,
    backgroundImage: `
      linear-gradient(rgba(30,50,65,0.3) 1px, transparent 1px),
      linear-gradient(90deg, rgba(30,50,65,0.3) 1px, transparent 1px)
    `,
    pointerEvents: "none",
  },
  loadingOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(10,15,20,0.85)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    zIndex: 200,
  },
  spinner: {
    width: 28,
    height: 28,
    border: `2px solid ${colors.border}`,
    borderTop: `2px solid ${colors.primary}`,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingText: {
    fontSize: 11,
    letterSpacing: "0.1em",
    color: colors.primary,
  },
  errorOverlay: {
    position: "absolute",
    bottom: 48,
    left: "50%",
    transform: "translateX(-50%)",
    background: "#2a1518",
    border: "1px solid #5a2a2a",
    borderRadius: radius.md,
    padding: "10px 16px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    zIndex: 200,
  },
  errorText: {
    fontSize: 11,
    color: colors.danger,
  },
  errorDismiss: {
    background: "none",
    border: "1px solid #5a2a2a",
    color: colors.danger,
    fontSize: 9,
    cursor: "pointer",
    padding: "3px 8px",
    borderRadius: radius.sm,
    letterSpacing: "0.06em",
  },
  emptyState: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    pointerEvents: "none",
  },
  dropIcon: {
    width: 64,
    height: 64,
    border: "2px dashed #1e3241",
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    color: "#2a4055",
  },
  emptyText: {
    fontSize: 12,
    color: colors.textDim,
    letterSpacing: "0.05em",
  },
  emptySubtext: {
    fontSize: 10,
    color: "#2a3d4d",
  },
  dragOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(74,144,164,0.08)",
    border: `2px dashed ${colors.primary}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    color: colors.primary,
    letterSpacing: "0.06em",
  },
};
