import { colors, font, radius } from "./tokens";

export const canvasStyles = {
  shell: {
    width: "100%",
    height: "100vh",
    background: colors.background,
    display: "flex",
    flexDirection: "column",
    fontFamily: font.sans,
    color: colors.textPrimary,
    overflow: "hidden",
    userSelect: "none",
  },
  canvas: {
    flex: 1,
    overflow: "hidden",
    cursor: "grab",
    position: "relative",
    background: colors.surface,
  },
  grid: {
    position: "absolute",
    inset: 0,
    backgroundImage: `
      linear-gradient(rgba(221,225,230,0.7) 1px, transparent 1px),
      linear-gradient(90deg, rgba(221,225,230,0.7) 1px, transparent 1px)
    `,
    pointerEvents: "none",
  },
  loadingOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(245,247,250,0.92)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    zIndex: 200,
  },
  spinner: {
    width: 28,
    height: 28,
    border: `2px solid ${colors.border}`,
    borderTop: `2px solid ${colors.accent}`,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingText: {
    fontSize: 13,
    fontWeight: 500,
    fontFamily: font.sans,
    color: colors.accent,
  },
  errorOverlay: {
    position: "absolute",
    bottom: 48,
    left: "50%",
    transform: "translateX(-50%)",
    background: "#FFF0F0",
    border: `1px solid ${colors.danger}`,
    borderRadius: radius.md,
    padding: "10px 16px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    zIndex: 200,
  },
  errorText: {
    fontSize: 13,
    fontFamily: font.sans,
    color: colors.danger,
  },
  errorDismiss: {
    background: "none",
    border: `1px solid ${colors.danger}`,
    color: colors.danger,
    fontSize: 11,
    fontFamily: font.sans,
    fontWeight: 500,
    cursor: "pointer",
    padding: "3px 10px",
    borderRadius: radius.sm,
  },
  emptyState: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    pointerEvents: "none",
  },
  dropIcon: {
    width: 64,
    height: 64,
    border: `2px dashed ${colors.border}`,
    borderRadius: radius.lg + 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    color: colors.textDim,
  },
  emptyText: {
    fontSize: 14,
    fontWeight: 500,
    fontFamily: font.sans,
    color: colors.textSecondary,
  },
  emptySubtext: {
    fontSize: 12,
    fontFamily: font.sans,
    color: colors.textDim,
  },
  dragOverlay: {
    position: "absolute",
    inset: 0,
    background: colors.accentGlow,
    border: `2px dashed ${colors.accent}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 600,
    fontFamily: font.sans,
    color: colors.accent,
  },
};
