import { colors, font, radius, spacing } from "./tokens";

export const dashboardStyles = {
  dashShell: {
    width: "100%",
    height: "100vh",
    background: colors.surface,
    display: "flex",
    flexDirection: "column",
    fontFamily: font.sans,
    color: colors.textPrimary,
    overflow: "hidden",
  },
  dashHeader: {
    height: 60,
    minHeight: 60,
    background: colors.primary,
    borderBottom: `1px solid ${colors.primaryLight}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
  },
  dashTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: colors.textOnDark,
    fontFamily: font.sans,
  },
  dashHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  dashCreateBtn: {
    background: colors.accent,
    border: "none",
    color: colors.textOnDark,
    fontSize: 13,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "7px 16px",
    borderRadius: radius.md,
    transition: "background 0.15s ease",
  },
  dashGrid: {
    flex: 1,
    overflowY: "auto",
    padding: spacing.lg,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: spacing.md,
    alignContent: "start",
  },
  dashCard: {
    background: colors.background,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    padding: "16px 18px",
    cursor: "pointer",
    position: "relative",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  dashCardTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  dashCardName: {
    fontSize: 14,
    fontWeight: 500,
    color: colors.textPrimary,
    fontFamily: font.sans,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dashCardMeta: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: font.sans,
  },
  dashDeleteBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    background: "none",
    border: "none",
    color: colors.textDim,
    fontSize: 12,
    cursor: "pointer",
    padding: "3px 6px",
    borderRadius: radius.sm,
    lineHeight: 1,
    transition: "color 0.15s ease",
  },
  dashCentered: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  dashEmpty: {
    fontSize: 14,
    color: colors.textSecondary,
    fontFamily: font.sans,
  },
};
