import { colors, font, radius, spacing } from "./tokens";

export const dashboardStyles = {
  dashShell: {
    width: "100%",
    height: "100vh",
    background: colors.surface,
    display: "flex",
    flexDirection: "column",
    fontFamily: font.sans,
    color: colors.textPrimary,
    overflow: "hidden",
  },

  /* ── Header ── */
  dashHeader: {
    minHeight: 64,
    background: colors.primary,
    borderBottom: `1px solid ${colors.primaryLight}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 28px",
    flexShrink: 0,
  },
  dashHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  dashLogo: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    background: "linear-gradient(135deg, #0096D6 0%, #00B4D8 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
    flexShrink: 0,
    letterSpacing: "0.04em",
  },
  dashBranding: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  dashTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: colors.textOnDark,
    fontFamily: font.sans,
    lineHeight: 1.1,
  },
  dashSubtitle: {
    fontSize: 11,
    color: "#6BA3BE",
    fontFamily: font.sans,
    fontWeight: 400,
    letterSpacing: "0.02em",
  },
  dashHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  dashCreateBtn: {
    background: colors.accent,
    border: "none",
    color: colors.textOnDark,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "8px 18px",
    borderRadius: radius.md,
    transition: "background 0.15s ease",
    letterSpacing: "0.01em",
  },

  /* ── Stats bar ── */
  dashStats: {
    background: colors.background,
    borderBottom: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    padding: "0 28px",
    gap: 0,
    height: 52,
    flexShrink: 0,
  },
  dashStat: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingRight: 28,
    marginRight: 28,
    borderRight: `1px solid ${colors.border}`,
  },
  dashStatLast: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  dashStatIcon: {
    width: 28,
    height: 28,
    borderRadius: radius.sm,
    background: "rgba(0,150,214,0.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    flexShrink: 0,
  },
  dashStatValue: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.textPrimary,
    lineHeight: 1,
  },
  dashStatLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    fontFamily: font.sans,
    lineHeight: 1,
    marginTop: 1,
  },

  /* ── Grid ── */
  dashGrid: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 28px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: 16,
    alignContent: "start",
  },

  /* ── Card ── */
  dashCard: {
    background: colors.background,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    padding: "18px 18px 14px",
    cursor: "pointer",
    position: "relative",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease, transform 0.12s ease",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  dashCardAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 4,
    height: "100%",
    borderRadius: `${radius.lg}px 0 0 ${radius.lg}px`,
    background: `linear-gradient(180deg, ${colors.accent} 0%, #00B4D8 100%)`,
  },
  dashCardTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    paddingLeft: 8,
  },
  dashCardName: {
    fontSize: 14,
    fontWeight: 600,
    color: colors.textPrimary,
    fontFamily: font.sans,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: 1.3,
    paddingRight: 24,
  },
  dashCardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    paddingLeft: 8,
  },
  dashCardMetaItem: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: colors.textSecondary,
    fontFamily: font.sans,
  },
  dashCardMetaDot: {
    width: 3,
    height: 3,
    borderRadius: "50%",
    background: colors.border,
    flexShrink: 0,
  },
  dashDeleteBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    background: "none",
    border: "1px solid transparent",
    color: colors.textDim,
    fontSize: 11,
    cursor: "pointer",
    padding: "3px 6px",
    borderRadius: radius.sm,
    lineHeight: 1,
    transition: "color 0.15s ease, border-color 0.15s ease",
  },

  /* ── Empty / loading states ── */
  dashCentered: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  dashEmptyIcon: {
    width: 64,
    height: 64,
    borderRadius: radius.lg,
    background: colors.surfaceAlt,
    border: `2px dashed ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 26,
    color: colors.textDim,
  },
  dashEmpty: {
    fontSize: 14,
    color: colors.textSecondary,
    fontFamily: font.sans,
    textAlign: "center",
  },
  dashEmptyHint: {
    fontSize: 12,
    color: colors.textDim,
    fontFamily: font.sans,
    textAlign: "center",
  },

  /* ── Footer ── */
  dashFooter: {
    borderTop: `1px solid ${colors.border}`,
    background: colors.background,
    padding: "10px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
    gap: 12,
    flexWrap: "wrap",
  },
  dashFooterLeft: {
    fontSize: 11,
    color: colors.textDim,
    fontFamily: font.sans,
  },
  dashFooterRight: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  dashLegalBtn: {
    background: "none",
    border: "none",
    color: colors.textDim,
    fontSize: 11,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: 0,
    textDecoration: "underline",
    textDecorationColor: "transparent",
    transition: "color 0.15s, text-decoration-color 0.15s",
  },

  /* spinner / loading reused from elsewhere */
  spinner: {
    width: 28,
    height: 28,
    border: `2px solid ${colors.border}`,
    borderTop: `2px solid ${colors.accent}`,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  loadingText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: font.sans,
    letterSpacing: "0.05em",
  },
};
