import { colors, font, radius, spacing } from "./tokens";

export const dashboardStyles = {
  dashShell: {
    width: "100%",
    height: "100vh",
    background: colors.background,
    display: "flex",
    flexDirection: "column",
    fontFamily: font.mono,
    color: colors.textSecondary,
    overflow: "hidden",
  },
  dashHeader: {
    height: 56,
    minHeight: 56,
    background: colors.surface,
    borderBottom: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
  },
  dashTitle: {
    fontSize: 13,
    letterSpacing: "0.08em",
    color: colors.textPrimary,
  },
  dashHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  dashCreateBtn: {
    background: "#1a2a38",
    border: `1px solid ${colors.borderStrong}`,
    color: colors.textPrimary,
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: radius.sm + 1,
  },
  dashGrid: {
    flex: 1,
    overflowY: "auto",
    padding: spacing.lg,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
    gap: spacing.md,
    alignContent: "start",
  },
  dashCard: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    padding: "14px 16px",
    cursor: "pointer",
    position: "relative",
    transition: "border-color 0.15s ease",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  dashCardTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  dashCardName: {
    fontSize: 12,
    color: colors.textPrimary,
    letterSpacing: "0.04em",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dashCardMeta: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 10,
    color: colors.textMuted,
    letterSpacing: "0.03em",
  },
  dashDeleteBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    background: "none",
    border: "none",
    color: colors.textDim,
    fontSize: 11,
    cursor: "pointer",
    padding: "2px 5px",
    borderRadius: radius.sm - 1,
    lineHeight: 1,
  },
  dashCentered: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  dashEmpty: {
    fontSize: 12,
    color: colors.textDim,
    letterSpacing: "0.04em",
  },
};
