import { colors, font, radius } from "./tokens";

export const panelStyles = {
  panel: {
    width: 300,
    minWidth: 300,
    background: colors.background,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    fontFamily: font.sans,
  },
  panelHeader: {
    padding: "12px 16px 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: `1px solid ${colors.border}`,
  },
  panelTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: colors.primary,
    fontFamily: font.sans,
  },
  panelCount: {
    fontSize: 11,
    fontWeight: 500,
    color: colors.textSecondary,
    background: colors.surface,
    padding: "2px 8px",
    borderRadius: 10,
    border: `1px solid ${colors.border}`,
  },
  panelSearch: {
    padding: "10px 16px 6px",
    position: "relative",
  },
  searchInput: {
    width: "100%",
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    color: colors.textPrimary,
    padding: "7px 28px 7px 10px",
    fontSize: 13,
    fontFamily: font.sans,
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s ease",
  },
  searchClear: {
    position: "absolute",
    right: 22,
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    color: colors.textSecondary,
    fontSize: 12,
    cursor: "pointer",
    padding: "2px 4px",
  },
  searchNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "4px 16px 8px",
  },
  navArrow: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    color: colors.textPrimary,
    fontSize: 11,
    cursor: "pointer",
    padding: "4px 12px",
    borderRadius: radius.sm,
    fontFamily: font.sans,
    fontWeight: 500,
    transition: "background 0.15s ease",
  },
  navCounter: {
    fontSize: 12,
    fontWeight: 500,
    color: colors.textPrimary,
    minWidth: 60,
    textAlign: "center",
    fontFamily: font.sans,
  },
  sizeControl: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 16px",
    borderBottom: `1px solid ${colors.border}`,
  },
  sizeLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: colors.textSecondary,
    fontFamily: font.sans,
  },
  sizeButtons: { display: "flex", alignItems: "center", gap: 6 },
  sizeBtn: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    color: colors.textPrimary,
    fontSize: 14,
    cursor: "pointer",
    width: 24,
    height: 24,
    borderRadius: radius.sm,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.15s ease",
  },
  sizeValue: {
    fontSize: 12,
    fontWeight: 500,
    color: colors.textPrimary,
    minWidth: 36,
    textAlign: "center",
    fontFamily: font.sans,
  },
  addBtn: {
    margin: "8px 16px",
    padding: "8px 0",
    border: "none",
    borderRadius: radius.md,
    fontSize: 12,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    transition: "background 0.15s ease",
  },
  placementHint: {
    padding: "0 16px 8px",
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: "center",
    fontFamily: font.sans,
  },
  nodeList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "6px 8px",
  },
  emptyList: {
    padding: "32px 16px",
    textAlign: "center",
    fontSize: 13,
    color: colors.textDim,
    fontFamily: font.sans,
  },
  nodeRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 10px",
    borderRadius: radius.sm,
    border: `1px solid ${colors.border}`,
    marginBottom: 3,
    background: colors.background,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    transition: "background 0.15s ease, border-color 0.15s ease",
  },
  nodeName: {
    fontSize: 13,
    fontWeight: 400,
    color: colors.textPrimary,
    cursor: "pointer",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    paddingRight: 8,
    fontFamily: font.sans,
  },
  nodeActions: {
    display: "flex",
    gap: 4,
    flexShrink: 0,
  },
  actionBtn: {
    background: "none",
    border: "none",
    color: colors.textSecondary,
    fontSize: 13,
    cursor: "pointer",
    padding: "2px 5px",
    borderRadius: radius.sm,
    lineHeight: 1,
    transition: "color 0.15s ease",
  },
  editInput: {
    flex: 1,
    background: colors.surfaceAlt,
    border: `1px solid ${colors.accent}`,
    borderRadius: radius.sm,
    color: colors.textPrimary,
    padding: "4px 8px",
    fontSize: 13,
    fontFamily: font.sans,
    outline: "none",
    marginRight: 8,
  },
  panelToggle: {
    width: 20,
    background: colors.surface,
    border: "none",
    borderLeft: `1px solid ${colors.border}`,
    color: colors.textSecondary,
    fontSize: 10,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "background 0.15s ease",
  },
};
