import { colors, font, radius } from "./tokens";

export const panelStyles = {
  panel: {
    width: 300,
    minWidth: 300,
    background: colors.surface,
    borderRight: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  panelHeader: {
    padding: "12px 14px 8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: `1px solid ${colors.border}`,
  },
  panelTitle: {
    fontSize: 11,
    letterSpacing: "0.08em",
    color: colors.textPrimary,
  },
  panelCount: {
    fontSize: 10,
    color: colors.textMuted,
    background: colors.surfaceAlt,
    padding: "2px 7px",
    borderRadius: 10,
  },
  panelSearch: {
    padding: "10px 14px 6px",
    position: "relative",
  },
  searchInput: {
    width: "100%",
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm + 1,
    color: colors.textPrimary,
    padding: "6px 28px 6px 10px",
    fontSize: 11,
    fontFamily: font.mono,
    outline: "none",
    letterSpacing: "0.03em",
  },
  searchClear: {
    position: "absolute",
    right: 20,
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    color: colors.textMuted,
    fontSize: 11,
    cursor: "pointer",
    padding: "2px 4px",
  },
  searchNav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "4px 14px 8px",
  },
  navArrow: {
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    color: colors.textPrimary,
    fontSize: 11,
    cursor: "pointer",
    padding: "4px 10px",
    borderRadius: radius.sm,
    fontFamily: font.mono,
  },
  navCounter: {
    fontSize: 11,
    color: colors.textPrimary,
    letterSpacing: "0.04em",
    minWidth: 60,
    textAlign: "center",
  },
  sizeControl: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 14px",
    borderBottom: `1px solid ${colors.border}`,
  },
  sizeLabel: { fontSize: 9, letterSpacing: "0.08em", color: colors.textMuted },
  sizeButtons: { display: "flex", alignItems: "center", gap: 6 },
  sizeBtn: {
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    color: colors.textSecondary,
    fontSize: 14,
    cursor: "pointer",
    width: 22,
    height: 22,
    borderRadius: radius.sm,
    lineHeight: 1,
  },
  sizeValue: { fontSize: 11, color: colors.textPrimary, minWidth: 32, textAlign: "center" },
  addBtn: {
    margin: "6px 14px",
    padding: "7px 0",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: radius.sm + 1,
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    fontFamily: font.mono,
    transition: "all 0.15s ease",
  },
  placementHint: {
    padding: "0 14px 8px",
    fontSize: 9,
    color: colors.textMuted,
    letterSpacing: "0.04em",
    textAlign: "center",
  },
  nodeList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "4px 8px",
  },
  emptyList: {
    padding: "24px 14px",
    textAlign: "center",
    fontSize: 10,
    color: colors.textDim,
    letterSpacing: "0.04em",
  },
  nodeRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 8px",
    borderRadius: radius.sm,
    border: `1px solid ${colors.border}`,
    marginBottom: 2,
    transition: "background 0.1s ease",
  },
  nodeName: {
    fontSize: 11,
    color: "#a0b4be",
    cursor: "pointer",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    paddingRight: 8,
  },
  nodeActions: {
    display: "flex",
    gap: 4,
    flexShrink: 0,
  },
  actionBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    fontSize: 12,
    cursor: "pointer",
    padding: "2px 4px",
    borderRadius: radius.sm - 1,
    lineHeight: 1,
  },
  editInput: {
    flex: 1,
    background: colors.surfaceAlt,
    border: `1px solid ${colors.primary}`,
    borderRadius: radius.sm,
    color: "#e0e8ec",
    padding: "3px 8px",
    fontSize: 11,
    fontFamily: font.mono,
    outline: "none",
    marginRight: 8,
  },
  panelToggle: {
    width: 20,
    background: colors.surface,
    border: "none",
    borderRight: `1px solid ${colors.border}`,
    color: colors.textMuted,
    fontSize: 10,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
};
