import { colors, font, radius } from "./tokens";

export const topBarStyles = {
  authShell: {
    width: "100%",
    height: "100vh",
    background: colors.background,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  authLoadingText: {
    fontFamily: font.mono,
    fontSize: 11,
    letterSpacing: "0.1em",
    color: colors.textMuted,
  },
  topBar: {
    height: 48,
    minHeight: 48,
    background: colors.surface,
    borderBottom: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    gap: 12,
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    transition: "all 0.3s ease",
  },
  title: {
    fontSize: 13,
    letterSpacing: "0.06em",
    color: colors.textPrimary,
  },
  fileTypeBadge: {
    fontSize: 9,
    letterSpacing: "0.08em",
    color: colors.primary,
    background: "rgba(74,144,164,0.12)",
    padding: "2px 6px",
    borderRadius: radius.sm - 1,
    border: "1px solid rgba(74,144,164,0.2)",
  },
  placementLabel: {
    fontSize: 10,
    letterSpacing: "0.08em",
    transition: "color 0.3s ease",
  },
  pageNav: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: colors.surfaceAlt,
    borderRadius: radius.md,
    padding: "4px 8px",
    border: `1px solid ${colors.border}`,
  },
  pageBtn: {
    background: "none",
    border: "none",
    color: colors.textSecondary,
    fontSize: 10,
    cursor: "pointer",
    padding: "0 2px",
  },
  pageLabel: {
    fontSize: 10,
    color: colors.textPrimary,
    minWidth: 36,
    textAlign: "center",
  },
  zoomControls: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: colors.surfaceAlt,
    borderRadius: radius.md,
    padding: "4px 8px",
    border: `1px solid ${colors.border}`,
  },
  zoomBtn: {
    background: "none",
    border: "none",
    color: colors.textSecondary,
    fontSize: 16,
    cursor: "pointer",
    padding: "0 4px",
    lineHeight: 1,
  },
  zoomLabel: {
    fontSize: 11,
    color: colors.textPrimary,
    minWidth: 40,
    textAlign: "center",
  },
  resetBtn: {
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    color: colors.textSecondary,
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    padding: "5px 10px",
    borderRadius: radius.sm + 1,
  },
  loadBtn: {
    background: "#1a2a38",
    border: `1px solid ${colors.borderStrong}`,
    color: colors.textPrimary,
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    padding: "5px 10px",
    borderRadius: radius.sm + 1,
  },
  backBtn: {
    background: "none",
    border: `1px solid ${colors.border}`,
    color: colors.textMuted,
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    padding: "5px 10px",
    borderRadius: radius.sm + 1,
  },
  replaceBtn: {
    background: "#1a2030",
    border: "1px solid #3a4060",
    color: "#a0b0d0",
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    padding: "5px 10px",
    borderRadius: radius.sm + 1,
  },
  signOutBtn: {
    background: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    color: colors.textMuted,
    fontSize: 10,
    letterSpacing: "0.06em",
    cursor: "pointer",
    padding: "5px 10px",
    borderRadius: radius.sm + 1,
  },
  statusBar: {
    height: 28,
    minHeight: 28,
    background: colors.surface,
    borderTop: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    fontSize: 10,
    color: colors.textMuted,
    letterSpacing: "0.04em",
  },
};
