import { colors, font, radius } from "./tokens";

export const topBarStyles = {
  authShell: {
    width: "100%",
    height: "100vh",
    background: colors.surface,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  authLoadingText: {
    fontFamily: font.sans,
    fontSize: 13,
    fontWeight: 500,
    color: colors.textSecondary,
  },
  topBar: {
    height: 52,
    minHeight: 52,
    background: colors.primary,
    borderBottom: `1px solid ${colors.primaryLight}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    gap: 12,
    fontFamily: font.sans,
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    transition: "all 0.15s ease",
  },
  title: {
    fontSize: 14,
    fontWeight: 600,
    color: colors.textOnDark,
    fontFamily: font.sans,
  },
  fileTypeBadge: {
    fontSize: 10,
    fontWeight: 500,
    color: colors.accent,
    background: "rgba(0, 150, 214, 0.15)",
    padding: "2px 8px",
    borderRadius: radius.sm,
    border: "1px solid rgba(0, 150, 214, 0.3)",
    fontFamily: font.sans,
  },
  placementLabel: {
    fontSize: 11,
    fontWeight: 500,
    fontFamily: font.sans,
    transition: "color 0.15s ease",
  },
  pageNav: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(255,255,255,0.08)",
    borderRadius: radius.md,
    padding: "4px 8px",
    border: "1px solid rgba(255,255,255,0.12)",
  },
  pageBtn: {
    background: "none",
    border: "none",
    color: "rgba(255,255,255,0.7)",
    fontSize: 10,
    cursor: "pointer",
    padding: "0 2px",
    fontFamily: font.sans,
  },
  pageLabel: {
    fontSize: 11,
    color: colors.textOnDark,
    minWidth: 36,
    textAlign: "center",
    fontFamily: font.sans,
  },
  zoomControls: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(255,255,255,0.08)",
    borderRadius: radius.md,
    padding: "4px 8px",
    border: "1px solid rgba(255,255,255,0.12)",
  },
  zoomBtn: {
    background: "none",
    border: "none",
    color: "rgba(255,255,255,0.7)",
    fontSize: 16,
    cursor: "pointer",
    padding: "0 4px",
    lineHeight: 1,
  },
  zoomLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: colors.textOnDark,
    minWidth: 40,
    textAlign: "center",
    fontFamily: font.sans,
  },
  resetBtn: {
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: radius.sm,
    transition: "background 0.15s ease",
  },
  loadBtn: {
    background: colors.accent,
    border: "none",
    color: colors.textOnDark,
    fontSize: 12,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: radius.sm,
    transition: "background 0.15s ease",
  },
  backBtn: {
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: radius.sm,
    transition: "background 0.15s ease",
  },
  replaceBtn: {
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: radius.sm,
    transition: "background 0.15s ease",
  },
  signOutBtn: {
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "rgba(255,255,255,0.6)",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: font.sans,
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: radius.sm,
    transition: "background 0.15s ease",
  },
  statusBar: {
    height: 28,
    minHeight: 28,
    background: colors.surface,
    borderTop: `1px solid ${colors.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    fontSize: 11,
    fontFamily: font.sans,
    color: colors.textSecondary,
  },
};
